### ISSUE TITLE
Please finish missing bits to make ProtocolBuffers a first class citizen in Scala

### ISSUE THREAD

**Issue by redbaron** [SandroGrzicic/ScalaBuff#27]
Even though ScalaBuff itself works ok and produces .scala file it is still not clear how to make use of it in sbt project. scalabuff branch of sbt-protobuf doesnt even compile and relies on some ScalaBuff modifications which you decided no  to merge, sbt dependencies are set to non-existing artifactIDs, etc.. So overall state of Protocol Buffers support in Scala is half done and  without sbt plugin there is really a very little use of your work ;(

In fact I believe that there is very little work needed to be done to bring sbt-protobuff plugin into a good shape (or even fork it under sbt-scalabuff name dropping all protoc compatibility) and make a nice minimalistic sbt project example with single .proto file and small app  which serializes and deserializes sample object. It have to be polished to the state, so that anyone can clone it, run "sbt package" and be ready to run "scala project.jar".

I'd be glad to help you dealing with it, even though I have very limited experience in Java/Scala. I forked gseit's versions of ScalaBuff, sbt-protobuf and sbt-protobuf-example and made them work together up to the point when final jar is assembled in sbt-protobuf-example, where some conflict occurs. I believe it happened because both java and scala version of object with the same name are bundled together into single jar, but I could be totally wrong ;)

Guys, you've done a great work to make it happen, few steps are missing, lets do them in one wat or another.

**Comment by redbaron** [comment]
10 years anniversary passed, time to close :)

**Comment by dispalt** [comment]
RIP =)
