### ISSUE TITLE
scalabuff-compiler should import @beans.BeanProperty instead of @reflect.BeanProperty when using scala 2.11.

### ISSUE THREAD

**Issue by rafael-brandao** [SandroGrzicic/ScalaBuff#80]
Hi Sandro.

Unfortunately this is critical for Scala 2.11 versions of scalabuff.

When using Scala 2.11 and scalabuff-compiler_2.11 (version 1.38), generated scala code imports lots of `@reflect.BeanProperty` when it should be importing `@beans.BeanProperty`.

Thanks in advance.

**Comment by SandroGrzicic** [comment]
Since 1.4.0 has now been released for Scala 2.10 and 2.11 and support for Scala 2.9 was dropped (now we always use beans.BeanProperty), I consider this issue resolved.
